### ISSUE TITLE
version 0.4.0 seems not work in hasura commutiy  svelte apollo example

### ISSUE THREAD

**Issue by windyboy** [timhall/svelte-apollo#107]
The  example code work fine with version 0.3.0.
When I try to upgrade to 0.4.0 goes wrong.

error message:
Uncaught (in promise) Invariant Violation: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag?

**Comment by quasarchimaere** [comment]
i also get the invariant violation, in my chrome network tab i see that the server is responding with the proper payload, could this mean that there is some issue with the InMemoryCache? (i upgraded svelte-apollo and apollo at the same time in order to get it out of the way, but so far this has not come to fruition)

**Comment by quasarchimaere** [comment]
> i also get the invariant violation, in my chrome network tab i see that the server is responding with the proper payload, could this mean that there is some issue with the InMemoryCache? (i upgraded svelte-apollo and apollo at the same time in order to get it out of the way, but so far this has not come to fruition)

i am sorry, i just realized that this was due to a subcomponent that hasn't been refactored to the new query parameter list and therefore it did pass the `client` object into the part where the query would have gone
