### ISSUE TITLE
Strange things using component in #await

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#21]
### Reproduction

- go to https://codesandbox.io/s/gifted-water-pcl7i
- click on "Articles"
- the Articles list shows
- but as you can see the text "Loading text in component..." is still present
- now uncomment line 26 and comment line 27 in `ArticlesPage.svelte`
- reload the page from codesandbox iframe button
- and as you can see the "Loading simple text..." is now removed when the load completes

**Why is this happening**, @timhall?

I tried with simple `svelte` components and everything works (but just for promises, not stores like the ones used in `svelte-apollo`): you can try it going to page "Loading w/o svelte-apollo" from top Navbar.

**Comment by frederikhors** [comment]
@timhall sorry for ping, I'm very stucked here. What it can be?

**Comment by timhall** [comment]
Seems likely to be a svelte bug. I’d try replacing `$articles` with a Promise and `setTimeout` to see if the issue persists. If that doesn’t reproduce it, it might be a store + promise issue. I can’t help much more now, but I’d try to make a simple example that doesn’t use svelte-apollo in the svelte REPL.

**Comment by frederikhors** [comment]
I understood the problem. If you open browser's console you can see:

```log
ArticlesPage.svelte? [sm]:29)
Uncaught (in promise) TypeError: Cannot read property 'articles' of undefined
    at create_then_block (
    at update (index.js:853)
    at eval (index.js:883)
```

From this code (https://codesandbox.io/s/gifted-water-pcl7i):

```html
  {#await $articles}
    <Loading/>
  {:then result}
    {#each result.data.articles as article (article.id)}
      <li>{article.id}</li>
    {:else}
      <li>No articles found</li>
    {/each}
  {:catch error}
    Error: {error}
  {/await}
```

to this code (https://codesandbox.io/s/stupefied-kowalevski-pskud):

```html
  {#await $articles}
    <Loading/>
  {:then result}
    {#if result.data}
      {#each result.data.articles as article (article.id)}
        <li>{article.id}</li>
      {:else}
        <li>No articles found</li>
      {/each}
    {:else}
      <Loading/>
    {/if}
  {:catch error}
    Error: {error}
  {/await}
```

So now I think we need `{#if result.data}` whenever there is `fetchPolicy: "cache-and-network"`, **but why**?

**Comment by timhall** [comment]
Looking at the docs that I could find for [FetchPolicy](https://github.com/apollographql/apollo-client/blob/1550fa3adccc83072e25a0b90ab80a39f70041bf/packages/apollo-client/src/core/watchQueryOptions.ts#L10) it does mention an "if available" check, which seems like it should avoid returning `undefined`. I'll run some tests and see what the expected behavior is, because it seems like it's returning `undefined` for the cache request and then the actual value once the network request completes. I'll also double-check the logic for setting initial values ([query.ts#L71](https://github.com/timhall/svelte-apollo/blob/83a92a0dea9518bb20ccabfd26f494114c9e9314/src/query.ts#L71)) to see if it is handling this case properly.
